[2023-05-24T15:40:26.726+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T15:40:26.743+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T15:40:26.743+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:40:26.743+0000] {taskinstance.py:1283} INFO - Starting attempt 11 of 11
[2023-05-24T15:40:26.743+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:40:26.769+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): token> on 2023-05-23 17:54:32.171118+00:00
[2023-05-24T15:40:26.777+0000] {standard_task_runner.py:55} INFO - Started process 950 to run task
[2023-05-24T15:40:26.784+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'token', 'manual__2023-05-23T17:54:32.171118+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp4yda5kxz']
[2023-05-24T15:40:26.785+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask token
[2023-05-24T15:40:26.906+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [running]> on host 2fa3ade57007
[2023-05-24T15:40:27.071+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=token
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T17:54:32.171118+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T17:54:32.171118+00:00
[2023-05-24T15:40:27.092+0000] {logging_mixin.py:137} INFO - None
[2023-05-24T15:40:27.542+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Spotify_ETL.py", line 60, in run_spotify_etl
    for song in resource['items']:
KeyError: 'items'
[2023-05-24T15:40:27.554+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=refresh_token, task_id=token, execution_date=20230523T175432, start_date=20230524T154026, end_date=20230524T154027
[2023-05-24T15:40:27.581+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task token ('items'; 950)
[2023-05-24T15:40:27.604+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-24T15:40:27.636+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
