[2023-05-24T15:30:23.368+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T15:30:23.384+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-24T15:30:23.384+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:30:23.384+0000] {taskinstance.py:1283} INFO - Starting attempt 7 of 11
[2023-05-24T15:30:23.385+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:30:23.412+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): token> on 2023-05-23 17:54:32.171118+00:00
[2023-05-24T15:30:23.421+0000] {standard_task_runner.py:55} INFO - Started process 673 to run task
[2023-05-24T15:30:23.423+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'token', 'manual__2023-05-23T17:54:32.171118+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp86y7nb89']
[2023-05-24T15:30:23.428+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask token
[2023-05-24T15:30:23.521+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.token manual__2023-05-23T17:54:32.171118+00:00 [running]> on host 2fa3ade57007
[2023-05-24T15:30:23.640+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=token
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T17:54:32.171118+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T17:54:32.171118+00:00
[2023-05-24T15:30:23.656+0000] {logging_mixin.py:137} INFO - None
[2023-05-24T15:30:23.817+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Spotify_ETL.py", line 60, in run_spotify_etl
    for song in resource['items']:
KeyError: 'items'
[2023-05-24T15:30:23.827+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=token, execution_date=20230523T175432, start_date=20230524T153023, end_date=20230524T153023
[2023-05-24T15:30:23.841+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 88 for task token ('items'; 673)
[2023-05-24T15:30:23.888+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-24T15:30:23.911+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
